mystr='Hello World'
print('This is Capitalize:')
print(mystr.capitalize())
print('=======================')
print('This is Swapcase:')
print(mystr.swapcase())
print('=======================')
print('This is Upper:')
print(mystr.upper())
print('=======================')
print('This is Lower:')
print(mystr.lower())
print('=======================')
print('This is Length:')
print(len(mystr))
print('=======================')
print('This is Replace:')
print(mystr.replace('World','Everyone'))
print('=======================')
print('This is Sub:')
sub='l'
print(mystr.count(sub))
print('=======================')
print('This is Startswith:')
print(mystr.startswith('Hello'))
print(mystr.startswith('World'))
print('=======================')
print('This is endwith:')
print(mystr.endswith('Hello'))
print(mystr.endswith('World'))
print('=======================')
print('This is Split:')
print(mystr.split())
print('=======================')
print('This is Find:')
print(mystr.find('World'))
print(mystr.find('world'))
print(mystr.find('H'))
print('=======================')
print('This is Index:')
print(mystr.index('r'))
print(mystr.index('World'))
print('=======================')
print('This is isalnum:')
mystr1='RahulSingh1'
mystr2='RahulSingh'
print(mystr1.isalnum())
print(mystr.isalnum())
print('=======================')
print('This is isalpha:')
print(mystr2.isalpha())
print(mystr1.isalpha())
print('=======================')
print('This is isnumeric:')
mystr3=1234
print(mystr.isnumeric())
mystr3='1234'
print(mystr3.isnumeric())
print('########################')
